name: amberol
version: 0.9.1
adopt-info: amberol
base: core22
grade: stable
confinement: strict
license: GPL-3.0+
compression: lzo

slots:
  # for GtkApplication registration
  amberol:
    interface: dbus
    bus: session
    name: io.bassi.Amberol
  mpris:
    name: Amberol

apps:
  amberol:
    environment:
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
    command: usr/bin/amberol
    extensions: [gnome]
    desktop: usr/share/applications/io.bassi.Amberol.desktop
    common-id: io.bassi.Amberol
    plugs:
      - home
      - audio-playback
      - removable-media
      - mount-observe
      - hostname-control
    slots:
      - mpris

parts:
  amberol:
    source: https://gitlab.gnome.org/World/amberol.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    plugin: meson
    meson-parameters:
      - --prefix=/snap/amberol/current/usr
    parse-info: [usr/share/metainfo/io.bassi.Amberol.appdata.xml]
    organize:
      snap/amberol/current: .
    build-packages:
      - intltool
      - rustc
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - cargo
      - execstack
    stage-packages:
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
    override-build: |
      # snapd can't use a name like io.bassi.Amberol for mpris
      # (since it contains periods) so instead make this just Amberol
      sed -i '0,/APPLICATION_ID.to_string()/{s/APPLICATION_ID.to_string()/"Amberol".to_string()/}' ../src/src/audio/mpris_controller.rs
      craftctl default

    override-prime: |
      set -eu
      craftctl default
      # try remove execstack on armhf
      for f in usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1 usr/lib/arm-linux-gnueabihf/libmpeg2.so.0.1.0; do
        if [ -f $f ]; then
          execstack -c $f
        fi
      done
