name: amberol
version: 0.9.1
adopt-info: amberol
base: core22
grade: stable
confinement: strict
license: GPL-3.0+
compression: lzo

slots:
  # for GtkApplication registration
  amberol:
    interface: dbus
    bus: session
    name: io.bassi.Amberol
  mpris:
    name: Amberol

apps:
  amberol:
    environment:
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
    command: usr/bin/amberol
    extensions: [gnome]
    desktop: usr/share/applications/io.bassi.Amberol.desktop
    common-id: io.bassi.Amberol
    plugs:
      - home
      - removable-media
      - audio-playback
      - mount-observe
      - hostname-control
    slots:
      - mpris

parts:
  amberol:
    source: https://gitlab.gnome.org/World/amberol.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    plugin: meson
    meson-parameters:
      - --prefix=/snap/amberol/current/usr
    organize:
      snap/amberol/current/usr: usr
    build-packages:
      - intltool
      - rustc
      - appstream
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - cargo
      - execstack
    stage-packages:
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
    override-build: |
      # snapd can't use a name like io.bassi.Amberol for mpris
      # (since it contains periods) so instead make this just Amberol
      sed -i '0,/APPLICATION_ID.to_string()/{s/APPLICATION_ID.to_string()/"Amberol".to_string()/}' ../src/src/audio/mpris_controller.rs
      craftctl default

    override-prime: |
      set -eu
      craftctl default
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/io.bassi.Amberol.svg|' usr/share/applications/io.bassi.Amberol.desktop
      # try remove execstack on armhf
      for f in usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1 usr/lib/arm-linux-gnueabihf/libmpeg2.so.0.1.0; do
        if [ -f $f ]; then
          execstack -c $f
        fi
      done
    parse-info: [usr/share/appdata/io.bassi.Amberol.appdata.xml]
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - amberol
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gtk-common-themes
      - gnome-42-2204
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
