name: amberol
adopt-info: amberol
base: core24
grade: stable
confinement: strict
license: GPL-3.0+
compression: lzo

slots:
  # for GtkApplication registration
  amberol:
    interface: dbus
    bus: session
    name: io.bassi.Amberol
  mpris:
    name: Amberol

apps:
  amberol:
    environment:
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
    command: usr/bin/amberol
    extensions: [gnome]
    desktop: usr/share/applications/io.bassi.Amberol.desktop
    common-id: io.bassi.Amberol
    plugs:
      - home
      - audio-playback
      - removable-media
      - mount-observe
      - hostname-control
      - screen-inhibit-control
    slots:
      - mpris

parts:
  amberol:
    source: https://gitlab.gnome.org/World/amberol.git
    source-tag: '0.10.3'
    plugin: meson
    meson-parameters:
      - --prefix=/snap/amberol/current/usr
      - -Dbuildtype=release
      - -Doptimization=2
    parse-info: [usr/share/appdata/io.bassi.Amberol.appdata.xml]
    organize:
      snap/amberol/current: .
    build-packages:
      - m4
      - rustc
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - cargo
      - git
    override-build: |
      # snapd can't use a name like io.bassi.Amberol for mpris
      # (since it contains periods) so instead make this just Amberol
      sed -i '0,/APPLICATION_ID.to_string()/{s/APPLICATION_ID.to_string()/"Amberol".to_string()/}' ../src/src/audio/mpris_controller.rs
      craftctl default

    override-prime: |
      craftctl default
      # Fix-up application icon lookup
      sed -i -e 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/io.bassi.Amberol.svg|' usr/share/applications/io.bassi.Amberol.desktop

  gstreamer-plugins:
    plugin: nil
    build-snaps:
      - core24
      - gnome-46-2404
    stage-packages:
      # needed for aac decoding - see
      # https://github.com/alexmurray/amberol-snap/issues/11 - note the gnome
      # SDK includes the various libgstreamer-plugins-xxx1.0-0 already so this
      # is not needed - only the actual plugin itself
      - gstreamer1.0-plugins-bad
    override-build: |
      set -eux
      craftctl default
      for snap in "core24" "gnome-46-2404"; do
        cd /snap/$snap/current/usr/lib/$CRAFT_ARCH_TRIPLET
        find . -type f,l -name "*.so*" -exec bash -c "rm -f $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/{}*" \;
      done
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/*.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET/*/*.so*
